### ISSUE TITLE
show logging from underlying celery beat instance

### ISSUE THREAD

**Issue by jadedarko** [ybrs/single-beat#22]
Is stdout for the child beat instance is only printed on termination of the parent single-beat instance?

I couldn't see a way to show this output, meaning my journalctl logs don't show task scheduling.

Is there a way to always print celery output in realtime to stdio?

**Comment by ybrs** [comment]
Again visiting this, maybe this should be optional ? like `SINGLE_BEAT_UNBUFFERED=1` and flush at each line, because on the other hand, we are doing a double buffering (if that is a correct term), as in, child might be wanting to flush each line and we'd be buffering. 

@robvdl What do you think about putting it into a config env. variable ? and making it optional ?

**Comment by robvdl** [comment]
Sounds good to me, I don't mind making it optional.

**Comment by robvdl** [comment]
Also flushing every line I don't think is a problem because:

1) beat doesn't log much at all
2) when it does, it always logs one line anyway "invoke task xyz"

Just my 2c

**Comment by s4ke** [comment]
Wouldn't the solution here be to "simply" run the child process in unbuffered mode?
